version: "3.8"

services:
  gap:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    command:  >             
          sh -c  "python manage.py makemigrations &&
          python manage.py migrate &&
          gunicorn gap.wsgi:application --bind 0.0.0.0:8000  --reload"
    depends_on:
      - db
    tty: true
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
     - POSTGRES_DB=${DB_NAME}
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
    
volumes:
  postgres_data: